# Generated by Django 5.1.7 on 2025-12-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="nom")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "cv_url",
                    models.URLField(
                        help_text="Lien vers le CV (PDF, Drive, S3, etc.)",
                        max_length=500,
                        verbose_name="URL du CV",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Validée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="candidature envoyée le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifiée le"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="job.job",
                        verbose_name="offre d'emploi",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidature",
                "verbose_name_plural": "candidatures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="candidate_c_status_f93937_idx"
                    ),
                    models.Index(fields=["job"], name="candidate_c_job_id_2c5c18_idx"),
                ],
            },
        ),
    ]
