# Generated by Django 5.2.10 on 2026-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code technique unique utilisé par le backend.",
                        max_length=60,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nom affiché dans l'interface.",
                        max_length=120,
                        verbose_name="libellé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description métier du type d'événement.",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Empêche la suppression si utilisé par la logique métier.",
                        verbose_name="événement système",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "type d'événement lead",
                "verbose_name_plural": "types d'événements lead",
                "ordering": ["label"],
            },
        ),
    ]
