# Generated by Django 5.2.10 on 2026-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadTaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Identifiant technique du type de tâche (ex: RAPPEL_RDV)",
                        max_length=50,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "type de tâche lead",
                "verbose_name_plural": "types de tâches lead",
                "ordering": ["label"],
            },
        ),
    ]
