# Generated by Django 5.2.10 on 2026-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadTaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="code"
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="libellé")),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si la tâche est terminée ou bloquée.",
                        verbose_name="statut final",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "statut tâche",
                "verbose_name_plural": "statuts tâches",
                "ordering": ["label"],
            },
        ),
    ]
