# Generated by Django 5.1.7 on 2026-05-18 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Code promotionnel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACTIVE", "Actif"),
                            ("PAUSED", "En pause"),
                            ("DISABLED", "Désactivé"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Taux de commission",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Créateur",
                "verbose_name_plural": "Profils Créateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialAccountLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("TIKTOK", "TikTok"),
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("YOUTUBE", "YouTube"),
                            ("LINKEDIN", "LinkedIn"),
                            ("OTHER", "Autre"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Plateforme",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="Nom d'utilisateur"),
                ),
                (
                    "profile_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL du profil"
                    ),
                ),
                (
                    "followers_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'abonnés"
                    ),
                ),
                (
                    "is_viable",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Viable"
                    ),
                ),
                (
                    "contact_status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouveau"),
                            ("TO_CONTACT", "À contacter"),
                            ("CONTACTED", "Contacté"),
                            ("POSITIVE", "Positif"),
                            ("NEGATIVE", "Négatif"),
                            ("CONVERTED", "Converti"),
                            ("NOT_RELEVANT", "Non pertinent"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="Statut du contact",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_leads",
                        to="creators.creatorprofile",
                        verbose_name="Créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte Social Prospect",
                "verbose_name_plural": "Comptes Sociaux Prospects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(fields=["status"], name="creators_cr_status_6a027d_idx"),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["promo_code"], name="creators_cr_promo_c_88c404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["created_at"], name="creators_cr_created_daed44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(
                fields=["platform"], name="creators_so_platfor_dffa9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(
                fields=["contact_status"], name="creators_so_contact_436497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(
                fields=["is_viable"], name="creators_so_is_viab_d371d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(
                fields=["created_at"], name="creators_so_created_e5fb04_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccountlead",
            constraint=models.UniqueConstraint(
                fields=("platform", "username"), name="unique_platform_username"
            ),
        ),
    ]
