# Generated by Django 5.1.7 on 2026-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccountlead",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Biographie"),
        ),
        migrations.AddField(
            model_name="socialaccountlead",
            name="categories",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Exemple : business, emploi, lifestyle, étudiant",
                max_length=255,
                null=True,
                verbose_name="Catégories",
            ),
        ),
        migrations.AddField(
            model_name="socialaccountlead",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Pays",
            ),
        ),
        migrations.AddField(
            model_name="socialaccountlead",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom affiché"
            ),
        ),
        migrations.AddField(
            model_name="socialaccountlead",
            name="language",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                null=True,
                verbose_name="Langue",
            ),
        ),
        migrations.AddField(
            model_name="socialaccountlead",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Ligne CSV originale ou payload brut de scraping.",
                verbose_name="Données brutes",
            ),
        ),
        migrations.AddField(
            model_name="socialaccountlead",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Exemple : scrape_tiktok_ci_20260518, import_csv, manuel",
                max_length=150,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccountlead",
            name="profile_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL du profil"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(
                fields=["country"], name="creators_so_country_2c22b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(
                fields=["language"], name="creators_so_languag_c7debd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountlead",
            index=models.Index(fields=["source"], name="creators_so_source_60cae2_idx"),
        ),
    ]
