# Generated by Django 5.1.7 on 2026-05-26 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creators",
            "0002_socialaccountlead_bio_socialaccountlead_categories_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorprofile",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10.0,
                max_digits=5,
                null=True,
                verbose_name="Taux de commission",
            ),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="promo_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Code promotionnel",
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Taux de commission",
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Montant du bonus",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("INACTIVE", "Inactif"),
                            ("EXPIRED", "Expiré"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valide jusqu'au"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to="creators.creatorprofile",
                        verbose_name="Créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Promo",
                "verbose_name_plural": "Codes Promo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="creators_pr_status_316bb2_idx"
                    ),
                    models.Index(fields=["code"], name="creators_pr_code_fbbd64_idx"),
                    models.Index(
                        fields=["creator"], name="creators_pr_creator_7d0051_idx"
                    ),
                ],
            },
        ),
    ]
