# Generated by Django 5.1.7 on 2026-05-26 14:03
from django.db import migrations

def migrate_promo_codes(apps, schema_editor):
    CreatorProfile = apps.get_model('creators', 'CreatorProfile')
    PromoCode = apps.get_model('creators', 'PromoCode')
    Lead = apps.get_model('leads', 'Lead')

    for creator in CreatorProfile.objects.filter(promo_code__isnull=False).iterator():
        if creator.promo_code:
            promo_code_obj, created = PromoCode.objects.get_or_create(
                code=creator.promo_code,
                defaults={
                    'creator': creator,
                    'commission_rate': creator.commission_rate or 10.00,
                    'status': 'ACTIVE',
                    'description': 'Code promo migré automatiquement.'
                }
            )

            Lead.objects.filter(creator_profile=creator).update(promo_code=promo_code_obj)

class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0003_alter_creatorprofile_commission_rate_and_more"),
        ("leads", "0019_lead_promo_code"),
    ]

    operations = [
        migrations.RunPython(migrate_promo_codes, migrations.RunPython.noop),
    ]
