# Generated by Django 5.1.7 on 2026-05-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0004_data_migration_promo_codes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="creatorprofile",
            name="creators_cr_promo_c_88c404_idx",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="commission_rate",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="promo_code",
        ),
    ]
