# Generated by Django 5.1.7 on 2026-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creators",
            "0005_remove_creatorprofile_creators_cr_promo_c_88c404_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="currency",
            field=models.CharField(
                default="EUR",
                help_text="Ex: EUR, USD, XOF, etc.",
                max_length=3,
                verbose_name="Devise (Code ISO)",
            ),
        ),
    ]
