# Generated by Django 5.1.7 on 2026-05-26 14:53

import api.creators.models
import api.storage_backends
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0006_creatorprofile_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du contrat"),
                ),
                (
                    "file",
                    models.FileField(
                        storage=api.storage_backends.MinioCreatorContractStorage(),
                        upload_to=api.creators.models.creator_contract_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="creators.creatorprofile",
                        verbose_name="Créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat Créateur",
                "verbose_name_plural": "Contrats Créateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
