# Generated by Django 5.2.10 on 2026-03-13 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0014_remove_lead_blocking_duration_and_more"),
        ("leads_event_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données contextuelles : valeurs avant/après, paramètres, etc.",
                        verbose_name="données",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date de l'événement",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant déclenché l'événement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="leads_event_type.leadeventtype",
                        verbose_name="type d'événement",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Lead concerné par l'événement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="leads.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement lead",
                "verbose_name_plural": "événements lead",
                "ordering": ["occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "occurred_at"],
                        name="leads_event_lead_id_2f7026_idx",
                    ),
                    models.Index(
                        fields=["lead", "event_type"],
                        name="leads_event_lead_id_78e6ad_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="leads_event_actor_i_000a0f_idx"
                    ),
                ],
            },
        ),
    ]
