# Generated by Django 5.1.7 on 2026-04-22 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_add_document_type"),
        ("leads", "0016_lead_is_eligible"),
        ("leads_event_type", "0001_initial"),
        ("leads_events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leadevent",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="documents.document",
                verbose_name="documents liés",
            ),
        ),
        migrations.AddField(
            model_name="leadevent",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Événement parent dans l'arbre du cycle de vie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="leads_events.leadevent",
                verbose_name="événement parent",
            ),
        ),
        migrations.AddField(
            model_name="leadevent",
            name="position_x",
            field=models.FloatField(default=0.0, verbose_name="position X"),
        ),
        migrations.AddField(
            model_name="leadevent",
            name="position_y",
            field=models.FloatField(default=0.0, verbose_name="position Y"),
        ),
        migrations.AlterField(
            model_name="leadevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="acteur",
            ),
        ),
        migrations.AlterField(
            model_name="leadevent",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="données"),
        ),
        migrations.AlterField(
            model_name="leadevent",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="leads.lead",
                verbose_name="lead",
            ),
        ),
        migrations.AddIndex(
            model_name="leadevent",
            index=models.Index(
                fields=["lead", "parent_event"], name="leads_event_lead_id_ae48ce_idx"
            ),
        ),
    ]
