# Generated by Django 5.2.10 on 2026-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("ACCUEIL", "Accueil"),
                    ("JURISTE", "Juriste"),
                    ("CONSEILLER", "Conseiller"),
                    ("AVOCAT", "Avocat"),
                ],
                default="CONSEILLER",
                help_text="Rôle attribué à l'utilisateur",
                max_length=32,
                verbose_name="rôle",
            ),
        ),
    ]
