# Generated by Django 5.1.7 on 2026-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone de l'utilisateur",
                max_length=20,
                null=True,
                verbose_name="téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("ACCUEIL", "Accueil"),
                    ("JURISTE", "Juriste"),
                    ("CONSEILLER", "Conseiller"),
                    ("AVOCAT", "Avocat"),
                    ("CREATOR", "Créateur"),
                ],
                default="CONSEILLER",
                help_text="Rôle attribué à l'utilisateur",
                max_length=32,
                verbose_name="rôle",
            ),
        ),
    ]
