# Generated by Django 5.2.10 on 2026-03-13 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0014_remove_lead_blocking_duration_and_more"),
        ("leads_events", "0001_initial"),
        ("leads_task_status", "0001_initial"),
        ("leads_task_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "due_at",
                    models.DateTimeField(db_index=True, verbose_name="échéance"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="créée le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="complétée le"
                    ),
                ),
                (
                    "reschedule_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="nombre de replanifications"
                    ),
                ),
                (
                    "reschedule_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="historique des replanifications",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assignée à",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="leads.lead",
                        verbose_name="lead",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="leads_task_status.leadtaskstatus",
                        verbose_name="statut",
                    ),
                ),
                (
                    "task_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="leads_task_type.leadtasktype",
                        verbose_name="type de tâche",
                    ),
                ),
                (
                    "triggered_by_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_tasks",
                        to="leads_events.leadevent",
                        verbose_name="déclenchée par l'événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "tâche lead",
                "verbose_name_plural": "tâches lead",
                "ordering": ["due_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "due_at"], name="leads_task__lead_id_ae913e_idx"
                    ),
                    models.Index(
                        fields=["status", "due_at"],
                        name="leads_task__status__a9e85a_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="leads_task__assigne_97228a_idx",
                    ),
                ],
            },
        ),
    ]
