# Generated by Django 5.2.10 on 2026-03-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_task", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="leadtask",
            new_name="leads_task__status_499784_idx",
            old_name="leads_task__status__a9e85a_idx",
        ),
        migrations.RenameIndex(
            model_name="leadtask",
            new_name="leads_task__assigne_ae0844_idx",
            old_name="leads_task__assigne_97228a_idx",
        ),
        migrations.AlterField(
            model_name="leadtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "À faire"),
                    ("in_progress", "En cours"),
                    ("done", "Terminé"),
                    ("cancelled", "Annulé"),
                ],
                db_index=True,
                default="todo",
                max_length=30,
                verbose_name="statut",
            ),
        ),
    ]
