# Generated by Django 5.1.7 on 2026-04-08 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_lead_is_eligible"),
        ("leads_events", "0001_initial"),
        (
            "leads_task",
            "0002_rename_leads_task__status__a9e85a_idx_leads_task__status_499784_idx_and_more",
        ),
        ("leads_task_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadTaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="modifié"),
                ),
            ],
            options={
                "verbose_name": "commentaire tâche",
                "verbose_name_plural": "commentaires tâche",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="leadtask",
            name="estimated_duration",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="durée estimée (min)"
            ),
        ),
        migrations.AddField(
            model_name="leadtask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Basse"),
                    ("medium", "Normale"),
                    ("high", "Haute"),
                    ("urgent", "Urgente"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
                verbose_name="priorité",
            ),
        ),
        migrations.AddField(
            model_name="leadtask",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="tags"),
        ),
        migrations.AddIndex(
            model_name="leadtask",
            index=models.Index(
                fields=["priority", "status"], name="leads_task__priorit_5171b2_idx"
            ),
        ),
        migrations.AddField(
            model_name="leadtaskcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_task_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="auteur",
            ),
        ),
        migrations.AddField(
            model_name="leadtaskcomment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="leads_task.leadtask",
                verbose_name="tâche",
            ),
        ),
        migrations.AddIndex(
            model_name="leadtaskcomment",
            index=models.Index(
                fields=["task", "created_at"], name="leads_task__task_id_5922a5_idx"
            ),
        ),
    ]
