# Generated by Django 5.1.7 on 2026-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_task", "0003_leadtaskcomment_leadtask_estimated_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadtask",
            name="estimated_duration",
        ),
        migrations.RemoveField(
            model_name="leadtask",
            name="tags",
        ),
        migrations.AlterField(
            model_name="leadtask",
            name="priority",
            field=models.CharField(
                choices=[("medium", "Normale"), ("urgent", "Urgente")],
                db_index=True,
                default="medium",
                max_length=20,
                verbose_name="priorité",
            ),
        ),
    ]
