# Generated by Django 5.1.7 on 2026-01-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_lead_statut_dossier_interne"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure du dernier rappel J-1 envoyé (email et SMS)",
                null=True,
                verbose_name="dernier rappel envoyé",
            ),
        ),
    ]
