# Generated by Django 5.1.7 on 2026-01-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_lead_last_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("PRESENTIEL", "Présentiel"),
                    ("TELEPHONE", "Téléphonique"),
                    ("VISIO", "Visio"),
                ],
                default="PRESENTIEL",
                help_text="Mode du rendez-vous : présentiel, téléphonique ou visio",
                max_length=20,
                verbose_name="type de rendez-vous",
            ),
        ),
    ]
