# Generated by Django 5.2.10 on 2026-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_lead_appointment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("PRESENTIEL", "Présentiel"),
                    ("TELEPHONE", "Téléphonique"),
                    ("VISIO_CONFERENCE", "Visio-conférence"),
                ],
                default="PRESENTIEL",
                help_text="Mode du rendez-vous : présentiel, téléphonique ou visio",
                max_length=20,
                verbose_name="type de rendez-vous",
            ),
        ),
    ]
