# Generated by Django 5.2.10 on 2026-02-22 20:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_status", "0002_alter_leadstatus_label"),
        ("leads", "0012_alter_lead_appointment_type"),
        ("services", "0004_alter_service_code"),
        ("statut_dossier", "0002_alter_statutdossier_label"),
        ("statut_dossier_interne", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="blocking_duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="durée du blocage"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="department_code",
            field=models.CharField(
                blank=True,
                help_text="Département du prospect en France (ex: 75, 2A, 971)",
                max_length=10,
                verbose_name="département",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="is_urgent",
            field=models.BooleanField(default=False, verbose_name="situation urgente"),
        ),
        migrations.AddField(
            model_name="lead",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="services.service",
                verbose_name="service demandé",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Site internet"),
                    ("LANDING_PAGE", "Landing page"),
                    ("GOOGLE_SEARCH", "Recherche Google"),
                    ("GOOGLE_ADS", "Publicité Google Ads"),
                    ("SEO", "Résultat naturel (SEO)"),
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("TIKTOK", "TikTok"),
                    ("LINKEDIN", "LinkedIn"),
                    ("YOUTUBE", "YouTube"),
                    ("TWITTER", "Twitter / X"),
                    ("TIKTOK_LIVE", "Live TikTok"),
                    ("FACEBOOK_LIVE", "Live Facebook"),
                    ("INSTAGRAM_LIVE", "Live Instagram"),
                    ("YOUTUBE_LIVE", "Live YouTube"),
                    ("FACEBOOK_ADS", "Publicité Facebook"),
                    ("INSTAGRAM_ADS", "Publicité Instagram"),
                    ("TIKTOK_ADS", "Publicité TikTok"),
                    ("LINKEDIN_ADS", "Publicité LinkedIn"),
                    ("WORD_OF_MOUTH", "Bouche à oreille"),
                    ("REFERRAL_CLIENT", "Recommandation client"),
                    ("REFERRAL_PARTNER", "Recommandation partenaire"),
                    ("FRIEND_FAMILY", "Proche / famille"),
                    ("PARTNER", "Partenaire"),
                    ("ASSOCIATION", "Association"),
                    ("LAWYER", "Avocat"),
                    ("ACCOUNTANT", "Comptable"),
                    ("BUSINESS_CARD", "Carte de visite"),
                    ("STREET_POSTER", "Affiche dans la rue"),
                    ("FLYER", "Flyer"),
                    ("OFFICE_WALKIN", "Passage en agence"),
                    ("EVENT", "Événement / salon"),
                    ("COLD_CALL", "Appel sortant"),
                    ("INBOUND_CALL", "Appel entrant"),
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("BLOG", "Article de blog"),
                    ("PRESS", "Article presse"),
                    ("PODCAST", "Podcast"),
                    ("WEBINAR", "Webinaire"),
                    ("OTHER", "Autre"),
                ],
                default="WEBSITE",
                max_length=30,
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="appointment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de rendez-vous"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("PRESENTIEL", "Présentiel"),
                    ("TELEPHONE", "Téléphonique"),
                    ("VISIO_CONFERENCE", "Visio-conférence"),
                ],
                default="PRESENTIEL",
                max_length=20,
                verbose_name="type de rendez-vous",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="assignés à"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date de création"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="prénom"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="jurist_assigned",
            field=models.ManyToManyField(
                blank=True,
                related_name="leads_juriste",
                to=settings.AUTH_USER_MODEL,
                verbose_name="juristes assignés",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="dernier rappel envoyé"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="téléphone"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="lead_status.leadstatus",
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="statut_dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="statut_dossier.statutdossier",
                verbose_name="statut du dossier",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="statut_dossier_interne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="statut_dossier_interne.statutdossierinterne",
                verbose_name="statut du dossier interne",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["service"], name="lead_service_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["department_code"], name="lead_department_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["source"], name="lead_source_idx"),
        ),
    ]
