# Generated by Django 5.2.10 on 2026-02-22 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_status", "0002_alter_leadstatus_label"),
        ("leads", "0013_lead_blocking_duration_lead_department_code_and_more"),
        ("services", "0004_alter_service_code"),
        ("statut_dossier", "0002_alter_statutdossier_label"),
        ("statut_dossier_interne", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="blocking_duration",
        ),
        migrations.AddField(
            model_name="lead",
            name="blocking_duration_bucket",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_1_MONTH", "Moins d’1 mois"),
                    ("ONE_TO_THREE_MONTHS", "1 à 3 mois"),
                    ("THREE_TO_SIX_MONTHS", "3 à 6 mois"),
                    ("SIX_TO_TWELVE_MONTHS", "6 à 12 mois"),
                    ("MORE_THAN_ONE_YEAR", "Plus d’un an"),
                ],
                max_length=30,
                null=True,
                verbose_name="durée du blocage",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["blocking_duration_bucket"], name="lead_blocking_bucket_idx"
            ),
        ),
    ]
