# Generated by Django 5.2.10 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_remove_lead_blocking_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TITRE_SEJOUR", "Obtention de titre de séjour"),
                    ("REGROUPEMENT_FAM", "Regroupement familial"),
                    ("NATURALISATION", "Naturalisation"),
                    ("VISA", "Demande de visa"),
                    ("SUIVI_PREFECTURE", "Suivi de dossier en préfecture"),
                    ("DUPLICATA_SEJOUR", "Duplicata de titre de séjour"),
                    ("DCEM", "DCEM (Document de Circulation Enfant Mineur)"),
                    ("CREATION_ENTREPRISE", "Création d'entreprise"),
                    ("ASSISTANCE_JURIDIQUE", "Assistance juridique"),
                    ("OQTF", "Contestation OQTF"),
                    ("INSCRIPTION_UNIV", "Inscription universitaire"),
                    ("CASIER", "Effacement du casier judiciaire"),
                ],
                max_length=30,
                null=True,
                verbose_name="service demandé",
            ),
        ),
    ]
