# Generated by Django 5.2.10 on 2026-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0015_alter_lead_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_eligible",
            field=models.BooleanField(default=False, verbose_name="éligible"),
        ),
    ]
