# Generated by Django 5.1.7 on 2026-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_lead_is_eligible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Site internet"),
                    ("LANDING_PAGE", "Landing page"),
                    ("GOOGLE_SEARCH", "Recherche Google"),
                    ("GOOGLE_ADS", "Publicité Google Ads"),
                    ("SEO", "Résultat naturel (SEO)"),
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("TIKTOK", "TikTok"),
                    ("LINKEDIN", "LinkedIn"),
                    ("YOUTUBE", "YouTube"),
                    ("TWITTER", "Twitter / X"),
                    ("TIKTOK_LIVE", "Live TikTok"),
                    ("FACEBOOK_LIVE", "Live Facebook"),
                    ("INSTAGRAM_LIVE", "Live Instagram"),
                    ("YOUTUBE_LIVE", "Live YouTube"),
                    ("FACEBOOK_ADS", "Publicité Facebook"),
                    ("INSTAGRAM_ADS", "Publicité Instagram"),
                    ("TIKTOK_ADS", "Publicité TikTok"),
                    ("LINKEDIN_ADS", "Publicité LinkedIn"),
                    ("WORD_OF_MOUTH", "Bouche à oreille"),
                    ("REFERRAL_CLIENT", "Recommandation client"),
                    ("REFERRAL_PARTNER", "Recommandation partenaire"),
                    ("FRIEND_FAMILY", "Proche / famille"),
                    ("PARTNER", "Partenaire"),
                    ("ASSOCIATION", "Association"),
                    ("LAWYER", "Avocat"),
                    ("ACCOUNTANT", "Comptable"),
                    ("BUSINESS_CARD", "Carte de visite"),
                    ("STREET_POSTER", "Affiche dans la rue"),
                    ("FLYER", "Flyer"),
                    ("OFFICE_WALKIN", "Passage en agence"),
                    ("EVENT", "Événement / salon"),
                    ("COLD_CALL", "Appel sortant"),
                    ("INBOUND_CALL", "Appel entrant"),
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("KEMIA", "Agent Kemia (WhatsApp IA)"),
                    ("BLOG", "Article de blog"),
                    ("PRESS", "Article presse"),
                    ("PODCAST", "Podcast"),
                    ("WEBINAR", "Webinaire"),
                    ("OTHER", "Autre"),
                ],
                default="WEBSITE",
                max_length=30,
                verbose_name="source",
            ),
        ),
    ]
