# Generated by Django 5.1.7 on 2026-05-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creators",
            "0002_socialaccountlead_bio_socialaccountlead_categories_and_more",
        ),
        ("leads", "0017_alter_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="creator_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="creators.creatorprofile",
                verbose_name="Profil Créateur",
            ),
        ),
    ]
