# Generated by Django 5.1.7 on 2026-05-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0003_alter_creatorprofile_commission_rate_and_more"),
        ("leads", "0018_lead_creator_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="creators.promocode",
                verbose_name="Code Promo",
            ),
        ),
    ]
