# Generated by Django 5.1.7 on 2025-12-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jurist_availability_date", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="juristglobalavailability",
            new_name="jurist_avai_date_d59cc7_idx",
            old_name="jurist_avail_date_type_idx",
        ),
        migrations.RenameIndex(
            model_name="juristglobalavailability",
            new_name="jurist_avai_jurist__ddf791_idx",
            old_name="jurist_avail_jurist_date_idx",
        ),
    ]
