# Generated by Django 5.1.7 on 2025-12-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentreceipt_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceipt",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ESPECES", "Espèces"),
                    ("CB", "Carte bancaire"),
                    ("VIREMENT", "Virement bancaire"),
                    ("CHEQUE", "Chèque"),
                    ("PNF", "Crédit Cofidis (PNF)"),
                    ("PAYPAL", "PayPal"),
                    ("STRIPE", "Stripe"),
                    ("KLARNA", "Klarna"),
                    ("SCLP", "Scalapay"),
                    ("SCALA", "Scala"),
                    ("LENNBOX", "Lennbox"),
                    ("SEPA", "Prélèvement SEPA"),
                    ("AUTRE", "Autre / Non spécifié"),
                ],
                max_length=20,
            ),
        ),
    ]
