# Generated by Django 5.2.10 on 2026-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_date_expiration_visa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_anef_notification_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="date de la dernière notification ANEF",
            ),
        ),
    ]
