# Generated by Django 5.1.7 on 2026-04-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0016_lead_is_eligible"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_id", models.CharField(max_length=255, unique=True)),
                ("sender_phone", models.CharField(max_length=30)),
                ("body", models.TextField()),
                ("is_outbound", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyé"),
                            ("delivered", "Délivré"),
                            ("read", "Lu"),
                            ("failed", "Échec"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
