# Generated by Django 5.1.7 on 2026-04-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_lead_is_eligible"),
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappmessage",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("sent", "Envoyé"),
                    ("delivered", "Délivré"),
                    ("read", "Lu"),
                    ("failed", "Échec"),
                    ("received", "Reçu"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_messages",
                to="leads.lead",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="sender_phone",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
