# Generated by Django 5.1.7 on 2026-04-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_lead_is_eligible"),
        ("whatsapp", "0002_alter_whatsappmessage_delivery_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConversationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                (
                    "agent_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si False, l'agent ne répond plus automatiquement pour cette conversation.",
                        verbose_name="Agent IA actif",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_settings",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres conversation WhatsApp",
                "verbose_name_plural": "Paramètres conversations WhatsApp",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("lead__isnull", True)),
                        fields=("sender_phone",),
                        name="unique_unknown_phone_settings",
                    )
                ],
            },
        ),
    ]
