# Generated by Django 5.1.7 on 2026-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_whatsappconversationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_caption",
            field=models.TextField(
                blank=True,
                help_text="Légende optionnelle accompagnant le média",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_filename",
            field=models.CharField(
                blank=True,
                help_text="Nom de fichier original (pour les documents)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_id",
            field=models.CharField(
                blank=True,
                help_text="ID Meta du média (utilisé pour télécharger via l'API Graph)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_mime_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type du média (image/jpeg, audio/ogg;codecs=opus, video/mp4, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="media_url",
            field=models.TextField(
                blank=True,
                help_text="URL signée du média (valide ~5 min après récupération)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp réel du message (fourni par Meta ou auto au moment de la création)",
                null=True,
            ),
        ),
    ]
