# Generated by Django 5.2.10 on 2026-03-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = []
