# Generated by Django 5.1.7 on 2025-12-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Généré automatiquement à partir du titre",
                        max_length=255,
                        unique=True,
                        verbose_name="identifiant unique",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ex: Assistant(e) administratif(ve)",
                        max_length=255,
                        verbose_name="titre du poste",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Ex: Paris 17e, Paris / Hybride",
                        max_length=255,
                        verbose_name="lieu de travail",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Ex: CDI – Temps plein, CDD – 6 mois, Stage",
                        max_length=100,
                        verbose_name="type de contrat",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Résumé affiché dans la liste des offres (2-3 lignes)",
                        verbose_name="description courte",
                    ),
                ),
                (
                    "missions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des responsabilités et tâches du poste",
                        verbose_name="missions principales",
                    ),
                ),
                (
                    "profile",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des compétences et qualifications requises",
                        verbose_name="profil recherché",
                    ),
                ),
                (
                    "diploma",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Bac +2 minimum, Bac +3 en Droit",
                        max_length=255,
                        verbose_name="diplôme requis",
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Dès que possible, Janvier 2025 (optionnel)",
                        max_length=100,
                        verbose_name="date de début souhaitée",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour désactiver l'offre sans la supprimer",
                        verbose_name="offre active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "offre d'emploi",
                "verbose_name_plural": "offres d'emploi",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="job_job_is_acti_14d063_idx"
                    ),
                    models.Index(fields=["slug"], name="job_job_slug_4d0587_idx"),
                ],
            },
        ),
    ]
